version: "3.8"

services:
  tiny-url:
    image: n960321/tiny-url:latest
    ports: 
      - 8080:8080
    volumes: 
      - /Users/h_xian/Documents/playground/TinyURL/configs:/app/configs
      - /Users/h_xian/Documents/playground/TinyURL/deployment:/app/deployment
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15.5-alpine
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin

  redis:
    image: redis:7.2.3-alpine
    ports: 
      - 6379:6379
  
  prometheus:
    image: prom/prometheus:v2.48.1
    ports:
      - 9090:9090
    volumes:
      - /Users/h_xian/Documents/playground/TinyURL/deployment/prometheus:/etc/prometheus

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/h_xian/Documents/playground/TinyURL/deployment/promtail:/etc/promtail
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    
    