http:
  port: "8080"
db:
  type: "postgres"
  host: "tiny-url-db"
  port: 5432
  user: "postgres"
  password: "admin"
  db_name: "postgres"
  ssl_mode: "disable"
  migrate_path: "deployment/database/migrations"
cache:
  address: "tiny-url-cache"
  port: "6379"