http:
  port: "8080"
db:
  type: "postgres"
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "admin"
  db_name: "postgres"
  ssl_mode: "disable"
  migrate_path: "deployment/database/migrations"
cache:
  address: "redis"
  port: "6379"