@startuml
Actor User as user
collections Server as server
collections Cache as cache
database Database as db


user -> server : Send redirection request


group Exist in Cache 
    server -> cache : Check the url_key exist in the cache.
    cache -> user : If exist, reponse the original url.
end

group Exist in DB but not in Cache 
    server -> db : Query the url_key in the db.
    server -> cache: If exist, save in cache.
    server -> user: Reponse the original url.
end


server -> user: Reponse do not exist.

@enduml